class Events:
    PACKET_RECEIVED = "DATA_RECEIVED"

    SERVER_SHUTDOWN = "SERVER_SHUTDOWN"

    NEW_CLIENT_CONTROLLER = "NEW_CLIENT_CONTROLLER"
    CLIENT_CONNECT = "CLIENT_CONNECT"
    CLIENT_DISCONNECT = "CLIENT_DISCONNECT"
    CLIENT_TIME_UP = "CLIENT_TIME_UP"